### ISSUE TITLE
Credentials Required

### ISSUE THREAD

**Issue by AlexYoung28** [michelderooij/Invoke-Unarchive#1]
Hi, When i try to run this i’m getting

WARNING: Cannot bind to MsgFolderRoot: Exception calling “Bind” with “2” argument(s): “Credentials are required to make a service request.”

I’ve tried using $Credentials= Get-Credential but it doesnt seem to care i’ve applied that. It doesnt like me putting in -Credentials into the script with all the other bits.

.\Invoke-Unarchive.ps1 -Identity Alex@nsmit.biz -Impersonation -Server outlook.office365.com -Secret $mySecret -TenantId $tenantId -ClientId $clientId -Verbose

Am i doing something wrong?

**Comment by michelderooij** [comment]
Choose authentication method:
1. When using Basic Authentication, Credentials is required and your tenant needs to have BasicAuth enabled.
2. For Modern Auth, specifying TenantId, ClientId and one of Secret, CertificateThumbprint or CertificateFile (+optional CertificatePassword) is required for Modern Authentication/OAuth
